# Generated by Django 4.2.3 on 2023-11-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='burgers',
            name='PriceM',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
