# Generated by Django 4.2.3 on 2023-11-23 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Burgers',
            fields=[
                ('BurgerID', models.AutoField(primary_key=True, serialize=False)),
                ('BurgerName', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Image', models.URLField()),
                ('Ingredients', models.TextField()),
                ('Category', models.CharField(blank=True, max_length=50, null=True)),
                ('Calories', models.IntegerField(blank=True, null=True)),
                ('Rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
        ),
    ]
